// WAITING TRESHOLD

export const THRESHOLD = 400;

// RUNNER SETTINGS

export const RUNNER_SETTINGS = {
	HOUR_RATE: 85,
	WEIGHT_CONST: 7800,
	MAT_PRICE_PER_KG: 6,
	GRINDING_Q: 1.5,
	ALLOWANCE: 6,
};
